server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: appuser
    password: appuser
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans

welcome:
  message: Welcome to spring boot tutorial !!
